### ISSUE TITLE
Add Entity Framework event store

### ISSUE THREAD

**Issue by tsIgov** [Byteology/event-sourcing#2]
## Subtasks
- [x] Change the `IEventStore` interface so it can insert events in a transaction scope. The `IEventStore` should either be able to create a transaction / unit of work or it should be one itself. Don't forget to make the transaction object implement `IDisposable` and properly dispose it in the command handler code.
- [x] Create an abstract generic `DbContext` class that implements the `IEventStoreContext` interface.
- [x] The class should have a `DbSet<>` property of the generic type.
- [x] Create a default implementation of `IEventStoreContext`
- [x] Create a default implementation of `IEventStore`
